version: '2'
services:
  object_sharing-app:
    image: object_sharing
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://object_sharing-postgresql:5432/object_sharing
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  object_sharing-postgresql:
    extends:
      file: postgresql.yml
      service: object_sharing-postgresql
